brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
    # path(
    #     "",
    #     RedirectView.as_view(url=reverse_lazy("todo_list_list")),
    #     name="home",
    # ),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create"),
    path(
        "<int:pk>/edit/",
        TodoListUpdateView.as_view(),
        name="todo_list_update",
    ),
    path(
        "<int:pk>/delete/",
        TodoListDeleteView.as_view(),
        name="todo_list_delete",
    ),
    path(
        "items/create/", TodoItemCreateView.as_view(), name="todo_item_create"
    ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.task

todos/forms.py
from django.forms import CharField, ModelForm

from todos.models import TodoList


class TodoForm(ModelForm):
    name = CharField(max_length=100)

    class Meta:
        model = TodoList
        fields = ["name"]

todos/views.py
from django.shortcuts import render, redirect
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from todos.models import TodoList, TodoItem
from django.urls import reverse_lazy


class TodoListListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"
    # fields = ["task", "due_date", "is_completed", "list"]
    # context_object_name = "todo_list_detail"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     return context


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/update.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    fields = ["name"]
    success_url = reverse_lazy("todo_list_list")


# DOESNT WORK HERE
# def get_success_url(self):
#     return reverse_lazy("todo_list_list", args=[self.object.id])


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        # print("HEREEEEEEEEEEEEEE", self.object.__dict__)
        return reverse_lazy("todo_list_detail", args=[self.object.list_id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "items/update.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        # print("HEREEEEEEEEEEEEEE", self.object.__dict__)
        return reverse_lazy("todo_list_detail", args=[self.object.list_id])

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["TodoList"] = TodoItem.list
    #     return context

todos/templates/items/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new item</h1>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% comment %} <input type="text" name="Name"> {% endcomment %}
                    <p>
                        <button>Create</button>
                    </p>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/items/update.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Update Item</h1>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <button>Update</button>
                    </p>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new list</h1>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% comment %} <input type="text" name="Name"> {% endcomment %}
                    <p>
                        <button>Create</button>
                    </p>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Are you sure?</h1>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <button>Delete</button>
                    </p>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>{{ todolist.name }}</h1>
                <p>
                    <a href="{% url 'todo_list_update' todolist.pk %}">Edit</a>
                    <a href="{% url 'todo_list_delete' todolist.pk %}">Delete</a>
                </p>
                <h2>Tasks</h2>
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Due date</th>
                    </thead>
                    {% for list_item in todolist.items.all %}
                        <tbody>
                            <td>
                                <a href="{% url 'todo_item_update' list_item.pk %}">{{ list_item.task }}</a>
                            </td>
                            <td>{{ list_item.due_date }}</td>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Lists</h1>
                <p>
                    <a href="{% url 'todo_list_create' %}">Create a new list</a>
                </p>
                <p>
                    <a href="{% url 'todo_item_create' %}">Create a new item</a>
                </p>
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Number of items</th>
                    </thead>
                    {% for todolist in todolist_list %}
                        <tbody>
                            <td>
                                <a href="{% url 'todo_list_detail' todolist.pk %}">{{ todolist.name }}</a>
                            </td>
                            <td>{{ todolist.items.all|length }}</td>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/update.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Update List</h1>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <button>Update</button>
                    </p>
                </form>
            </div>
        </main>
    </body>
</html>